# Config file for GitHub Actions

name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest  # Fastest option

    steps:
      - name: Checkout code
        uses: actions/checkout@v6   # Copies code on VM

      - name: Set up Python
        uses: actions/setup-python@v5   # Official GitHub tool
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |            # Everything below will be treated as one line
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:    # Create env at virtual machine
            DJANGO_SETTINGS_MODULE: backend.config.settings # Show where is the brain of the project
        run: |
            python manage.py migrate
        

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: backend.config.settings
          PYTHONPATH: ${{ github.workspace }}  # github.workspace is a root dir, safe config
        run: |
            pytest --cov=backend/apps --cov-report=term-missing